version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/app/hob/database/database.sqlite
    volumes:
      - ./hob:/app/hob
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: railway
    ports:
      - "3306:3306"
