[build]
cmds = [
  "cd hob && /usr/local/bin/composer install --no-dev --no-interaction --prefer-dist",
  "cd hob && php artisan config:cache",
  "cd hob && php artisan route:cache",
  "cd hob && php artisan view:cache"
]

[start]
cmd = "cd hob && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"
