[phases.setup]
nixPkgs = ["php", "nodejs"]

[phases.install]
cmds = [
    "curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer",
    "chmod +x /usr/local/bin/composer",
    "cd hob && /usr/local/bin/composer install --no-dev --optimize-autoloader",
    "cd hob && npm ci",
    "cd hob && npm run build"
]

[start]
cmd = "cd hob && php artisan migrate --force && php artisan db:seed --force && php artisan serve --host=0.0.0.0 --port=$PORT"
