[phases.setup]
nixPkgs = ["php", "phpExtensions.composer", "nodejs"]

[phases.install]
cmds = [
    "cd hob && composer install --no-dev --optimize-autoloader",
    "cd hob && npm ci",
    "cd hob && npm run build"
]

[start]
cmd = "cd hob && php artisan migrate --force && php artisan db:seed --force && php artisan serve --host=0.0.0.0 --port=$PORT"
